var d,g=this;function aa(a){return void 0!==a}function q(a){return"string"==typeof a}function t(a){return"number"==typeof a}function ba(a,b){a=a.split(".");var c=g;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)!a.length&&aa(b)?c[e]=b:c=c[e]&&c[e]!==Object.prototype[e]?c[e]:c[e]={}}function ca(){}function da(a){a.Om=void 0;a.Hd=function(){return a.Om?a.Om:a.Om=new a}}
  function ea(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
  else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function u(a){return"array"==ea(a)}function fa(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length}function x(a){return"function"==ea(a)}function ha(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ia(a){return a[ja]||(a[ja]=++ka)}var ja="closure_uid_"+(1E9*Math.random()>>>0),ka=0;function la(a,b,c){return a.call.apply(a.bind,arguments)}
  function ma(a,b,c){if(!a)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function na(a,b,c){na=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?la:ma;return na.apply(null,arguments)}
  function oa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}function y(a,b){function c(){}c.prototype=b.prototype;a.m=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Vz=function(a,c,h){for(var e=Array(arguments.length-2),f=2;f<arguments.length;f++)e[f-2]=arguments[f];return b.prototype[c].apply(a,e)}};var pa;var qa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(q(a))return q(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ra=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=q(a)?a.split(""):a,h=0;h<e;h++)h in f&&b.call(c,f[h],h,a)},sa=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=
  a.length,e=[],f=0,h=q(a)?a.split(""):a,k=0;k<c;k++)if(k in h){var l=h[k];b.call(void 0,l,k,a)&&(e[f++]=l)}return e},ta=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=Array(e),h=q(a)?a.split(""):a,k=0;k<e;k++)k in h&&(f[k]=b.call(c,h[k],k,a));return f},ua=Array.prototype.every?function(a,b){return Array.prototype.every.call(a,b,void 0)}:function(a,b){for(var c=a.length,e=q(a)?a.split(""):a,f=0;f<c;f++)if(f in e&&!b.call(void 0,e[f],
  f,a))return!1;return!0};function va(a,b,c){a:{for(var e=a.length,f=q(a)?a.split(""):a,h=0;h<e;h++)if(h in f&&b.call(c,f[h],h,a)){b=h;break a}b=-1}return 0>b?null:q(a)?a.charAt(b):a[b]}function wa(a,b){return 0<=qa(a,b)}function xa(a,b){b=qa(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c}function ya(a){return Array.prototype.concat.apply([],arguments)}function za(a){var b=a.length;if(0<b){for(var c=Array(b),e=0;e<b;e++)c[e]=a[e];return c}return[]}
  function Aa(a,b){for(var c=1;c<arguments.length;c++){var e=arguments[c];if(fa(e)){var f=a.length||0,h=e.length||0;a.length=f+h;for(var k=0;k<h;k++)a[f+k]=e[k]}else a.push(e)}}function Ba(a,b,c,e){Array.prototype.splice.apply(a,Ca(arguments,1))}function Ca(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};function A(a,b){this.x=aa(a)?a:0;this.y=aa(b)?b:0}d=A.prototype;d.clone=function(){return new A(this.x,this.y)};function Da(a,b){return a==b?!0:a&&b?a.x==b.x&&a.y==b.y:!1}function Fa(a,b){var c=a.x-b.x;a=a.y-b.y;return Math.sqrt(c*c+a*a)}function Ga(a,b){return new A(a.x-b.x,a.y-b.y)}function Ha(a,b){return new A(a.x+b.x,a.y+b.y)}d.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};d.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
  d.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};d.translate=function(a,b){a instanceof A?(this.x+=a.x,this.y+=a.y):(this.x+=Number(a),t(b)&&(this.y+=b));return this};d.scale=function(a,b){b=t(b)?b:a;this.x*=a;this.y*=b;return this};
  var B={i:{}};B.i.yk="";B.i.Rb=!0;B.i.km=0;B.i.Aj="create";B.i.vw=B.i.Aj;B.i.El="delete";B.i.ww=B.i.El;B.i.zg="change";B.i.uw=B.i.zg;B.i.Oh="move";B.i.xw=B.i.Oh;B.i.Lo="var_create";B.i.Mo="var_delete";B.i.No="var_rename";B.i.Hj="ui";B.i.qo="comment_create";B.i.ro="comment_delete";B.i.po="comment_change";B.i.so="comment_move";B.i.Kh=[];B.i.M=function(a){B.i.isEnabled()&&(B.i.Kh.length||setTimeout(B.i.$t,0),B.i.Kh.push(a))};
  B.i.$t=function(){for(var a=B.i.filter(B.i.Kh,!0),b=B.i.Kh.length=0,c;c=a[b];b++){var e=Ia[c.hc]||null;if(e){var f=c;f.Rb&&(e.ug.push(f),e.$i.length=0,e.ug.length>e.xs&&e.ug.unshift());for(var h=0;c=e.ec[h];h++)c(f)}}};
  B.i.filter=function(a,b){a=za(a);b||a.reverse();for(var c=[],e=Object.create(null),f=0,h;h=a[f];f++)if(!h.dh()){var k=[h.type,h.Ib,h.hc].join(" "),l=e[k];l?h.type==B.i.Oh?(l.Zf=h.Zf,l.Yf=h.Yf,l.cf=h.cf):h.type==B.i.zg&&h.element==l.element&&h.name==l.name?l.newValue=h.newValue:h.type!=B.i.Hj||"click"!=h.element||"commentOpen"!=l.element&&"mutatorOpen"!=l.element&&"warningOpen"!=l.element?(e[k]=h,c.push(h)):l.newValue=h.newValue:(e[k]=h,c.push(h))}a=c.filter(function(a){return!a.dh()});b||a.reverse();
  for(f=1;h=a[f];f++)h.type==B.i.zg&&"mutation"==h.element&&a.unshift(a.splice(f,1)[0]);return a};B.i.ot=function(){for(var a=0,b;b=B.i.Kh[a];a++)b.Rb=!1};B.i.disable=function(){B.i.km++};B.i.enable=function(){B.i.km--};B.i.isEnabled=function(){return 0==B.i.km};B.i.$b=function(){return B.i.yk};B.i.T=function(a){B.i.yk="boolean"==typeof a?a?B.h.Ed():"":a};B.i.eq=function(a){var b=[];a=Ja(a,!1);for(var c=0,e;e=a[c];c++)b[c]=e.id;return b};
  B.i.Z=function(a,b){switch(a.type){case B.i.Aj:var c=new Ka(null);break;case B.i.El:c=new La(null);break;case B.i.zg:c=new Ma(null,"","","","");break;case B.i.Oh:c=new Na(null);break;case B.i.Lo:c=new Oa(null);break;case B.i.Mo:c=new Qa(null);break;case B.i.No:c=new Ra(null,"");break;case B.i.Hj:c=new Sa(null);break;case B.i.qo:c=new Ta(null);break;case B.i.po:c=new Ua(null);break;case B.i.so:c=new Va(null);break;case B.i.ro:c=new Wa(null);break;default:throw"Unknown event type.";}c.Z(a);c.hc=b.id;
  return c};B.i.eA=function(a){if(a.type==B.i.Oh||a.type==B.i.Aj){var b=Ia[a.hc]||null;if(a=Xa(b,a.Ib))if(a.getParent()&&!a.getParent().disabled){b=Ja(a,!1);a=0;for(var c;c=b[a];a++)c.lf(!1)}else if((a.S||a.X)&&!b.lb()){do a.lf(!0),a=Ya(a);while(a)}}};
  function Za(){this.hc=void 0;this.group=B.i.yk;this.Rb=B.i.Rb}Za.prototype.ua=function(){var a={type:this.type};this.group&&(a.group=this.group);return a};Za.prototype.Z=function(a){this.group=a.group};Za.prototype.dh=function(){return!1};Za.prototype.run=function(){};function $a(a){a=Ia[a.hc]||null;if(!a)throw Error("Workspace is null. Event must have been generated from real Blockly events.");return a};function ab(a){ab.m.constructor.call(this);this.Ib=a.id;this.hc=a.o.id}y(ab,Za);ab.prototype.ua=function(){var a=ab.m.ua.call(this);a.blockId=this.Ib;return a};ab.prototype.Z=function(a){ab.m.ua.call(this);this.Ib=a.blockId};function Ma(a,b,c,e,f){a&&(Ma.m.constructor.call(this,a),this.element=b,this.name=c,this.oldValue=e,this.newValue=f)}y(Ma,ab);B.i.ic=Ma;d=Ma.prototype;d.type=B.i.zg;
  d.ua=function(){var a=Ma.m.ua.call(this);a.element=this.element;this.name&&(a.name=this.name);a.newValue=this.newValue;return a};d.Z=function(a){Ma.m.Z.call(this,a);this.element=a.element;this.name=a.name;this.newValue=a.newValue};d.dh=function(){return this.oldValue==this.newValue};
  d.run=function(a){var b=Xa($a(this),this.Ib);if(b)switch(b.qe&&b.qe.la(!1),a=a?this.newValue:this.oldValue,this.element){case "field":(b=bb(b,this.name))?(cb(b,a),b.setValue(a)):console.warn("Can't set non-existent field: "+this.name);break;case "comment":b.cj(a||null);break;case "collapsed":b.hg(a);break;case "disabled":b.lf(a);break;case "inline":b.wh(a);break;case "mutation":var c="";b.ad&&(c=(c=b.ad())&&B.D.pc(c));if(b.Ne){a=a||"<mutation></mutation>";var e=B.D.Kc("<xml>"+a+"</xml>");b.Ne(e.firstChild)}B.i.M(new Ma(b,
  "mutation",null,c,a));break;default:console.warn("Unknown change type: "+this.element)}else console.warn("Can't change non-existent block: "+this.Ib)};function Ka(a){a&&(Ka.m.constructor.call(this,a),this.xml=a.o.P?B.D.Sl(a):B.D.Ke(a),this.Rf=B.i.eq(a))}y(Ka,ab);B.i.zj=Ka;Ka.prototype.type=B.i.Aj;Ka.prototype.ua=function(){var a=Ka.m.ua.call(this);a.xml=B.D.pc(this.xml);a.ids=this.Rf;return a};
  Ka.prototype.Z=function(a){Ka.m.Z.call(this,a);this.xml=B.D.Kc("<xml>"+a.xml+"</xml>").firstChild;this.Rf=a.ids};Ka.prototype.run=function(a){var b=$a(this);if(a)a=C("xml"),a.appendChild(this.xml),B.D.fe(a,b);else{a=0;for(var c;c=this.Rf[a];a++){var e=Xa(b,c);e?e.v(!1,!1):c==this.Ib&&console.warn("Can't uncreate non-existent block: "+c)}}};
  function La(a){if(a){if(a.getParent())throw"Connected blocks cannot be deleted.";La.m.constructor.call(this,a);this.ev=a.o.P?B.D.Sl(a):B.D.Ke(a);this.Rf=B.i.eq(a)}}y(La,ab);B.i.gs=La;La.prototype.type=B.i.El;La.prototype.ua=function(){var a=La.m.ua.call(this);a.ids=this.Rf;return a};La.prototype.Z=function(a){La.m.Z.call(this,a);this.Rf=a.ids};
  La.prototype.run=function(a){var b=$a(this);if(a){a=0;for(var c;c=this.Rf[a];a++){var e=Xa(b,c);e?e.v(!1,!1):c==this.Ib&&console.warn("Can't delete non-existent block: "+c)}}else a=C("xml"),a.appendChild(this.ev),B.D.fe(a,b)};function Na(a){a&&(Na.m.constructor.call(this,a),a=db(this),this.Tq=a.ir,this.Sq=a.vq,this.dn=a.rp)}y(Na,ab);B.i.Jh=Na;d=Na.prototype;d.type=B.i.Oh;
  d.ua=function(){var a=Na.m.ua.call(this);this.Zf&&(a.newParentId=this.Zf);this.Yf&&(a.newInputName=this.Yf);this.cf&&(a.newCoordinate=Math.round(this.cf.x)+","+Math.round(this.cf.y));return a};d.Z=function(a){Na.m.Z.call(this,a);this.Zf=a.newParentId;this.Yf=a.newInputName;a.newCoordinate&&(a=a.newCoordinate.split(","),this.cf=new A(parseFloat(a[0]),parseFloat(a[1])))};d.te=function(){var a=db(this);this.Zf=a.ir;this.Yf=a.vq;this.cf=a.rp};
  function db(a){var b=Xa(Ia[a.hc]||null,a.Ib);a={};var c=b.getParent();if(c){a.ir=c.id;a:{for(var e=0,f;f=c.W[e];e++)if(f.connection&&D(f.connection)==b){b=f;break a}b=null}b&&(a.vq=b.name)}else a.rp=b.ka();return a}d.dh=function(){return this.Tq==this.Zf&&this.Sq==this.Yf&&Da(this.dn,this.cf)};
  d.run=function(a){var b=$a(this),c=Xa(b,this.Ib);if(c){var e=a?this.Zf:this.Tq,f=a?this.Yf:this.Sq;a=a?this.cf:this.dn;var h=null;if(e&&(h=Xa(b,e),!h)){console.warn("Can't connect to non-existent block: "+e);return}c.getParent()&&eb(c);if(a)f=c.ka(),c.moveBy(a.x-f.x,a.y-f.y);else{c=c.S||c.X;if(f){if(b=fb(h,f))var k=b.connection}else c.type==B.Ge&&(k=h.R);k?c.connect(k):console.warn("Can't connect to non-existent input: "+f)}}else console.warn("Can't move non-existent block: "+this.Ib)};B.ya={};B.ya.mm=0;B.ya.ak=null;B.ya.Qt=function(a){var b=a.o,c=a.N();b.mc.play("delete");a=gb(b,c);c=c.cloneNode(!0);c.Wv=a.x;c.Xv=a.y;c.setAttribute("transform","translate("+a.x+","+a.y+")");E(b).appendChild(c);c.Vo=c.getBBox();B.ya.Rp(c,b.s,new Date,b.scale)};B.ya.Rp=function(a,b,c,e){var f=(new Date-c)/150;1<f?F(a):(a.setAttribute("transform","translate("+(a.Wv+(b?-1:1)*a.Vo.width*e/2*f)+","+(a.Xv+a.Vo.height*e*f)+") scale("+(1-f)*e+")"),setTimeout(B.ya.Rp,10,a,b,c,e))};
  B.ya.vt=function(a){var b=a.o,c=b.scale;b.mc.play("click");if(!(1>c)){var e=gb(b,a.N());a.S?(e.x+=(a.s?3:-3)*c,e.y+=13*c):a.X&&(e.x+=(a.s?-23:23)*c,e.y+=3*c);a=B.h.A("circle",{cx:e.x,cy:e.y,r:0,fill:"none",stroke:"#888","stroke-width":10},E(b));B.ya.pp(a,new Date,c)}};B.ya.pp=function(a,b,c){var e=(new Date-b)/150;1<e?F(a):(a.setAttribute("r",25*e*c),a.style.opacity=1-e,B.ya.mm=setTimeout(B.ya.pp,10,a,b,c))};
  B.ya.Pt=function(a){a.o.mc.play("disconnect");if(!(1>a.o.scale)){var b=a.tb().height;b=Math.atan(10/b)/Math.PI*180;a.s||(b*=-1);B.ya.Qp(a.N(),b,new Date)}};B.ya.Qp=function(a,b,c){var e=(new Date-c)/200;1<e?a.ng="":(a.ng="skewX("+Math.round(Math.sin(e*Math.PI*3)*(1-e)*b)+")",B.ya.ak=a,B.ya.mm=setTimeout(B.ya.Qp,10,a,b,c));a.setAttribute("transform",a.Ce+a.ng)};B.ya.nm=function(){if(B.ya.ak){clearTimeout(B.ya.mm);var a=B.ya.ak;a.ng="";a.setAttribute("transform",a.Ce);B.ya.ak=null}};function hb(a,b){return 0==a.lastIndexOf(b,0)}function ib(a){return/^[\s\xa0]*$/.test(a)}function jb(a){return a.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"")}var kb=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
  function lb(a){if(!mb.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(nb,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ob,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(pb,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(qb,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(rb,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(sb,"&#0;"));return a}var nb=/&/g,ob=/</g,pb=/>/g,qb=/"/g,rb=/'/g,sb=/\x00/g,mb=/[\x00&<>"']/;
  function tb(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'};var c=g.document.createElement("div");return a.replace(ub,function(a,f){var e=b[a];if(e)return e;"#"==f.charAt(0)&&(f=Number("0"+f.substr(1)),isNaN(f)||(e=String.fromCharCode(f)));e||(c.innerHTML=a+" ",e=c.firstChild.nodeValue.slice(0,-1));return b[a]=e})}
  function vb(a){return a.replace(/&([^;]+);/g,function(a,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:return"#"!=c.charAt(0)||(c=Number("0"+c.substr(1)),isNaN(c))?a:String.fromCharCode(c)}})}var ub=/&([^;\s<&]+);?/g;function wb(a,b){return a<b?-1:a>b?1:0}function xb(){return"background-color".replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()})}
  function yb(a){var b=q(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,f){return b+f.toUpperCase()})};var zb;a:{var Ab=g.navigator;if(Ab){var Bb=Ab.userAgent;if(Bb){zb=Bb;break a}}zb=""}function Cb(a){return-1!=zb.indexOf(a)};function Db(a,b,c){for(var e in a)b.call(c,a[e],e,a)}var Eb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Fb(a,b){for(var c,e,f=1;f<arguments.length;f++){e=arguments[f];for(c in e)a[c]=e[c];for(var h=0;h<Eb.length;h++)c=Eb[h],Object.prototype.hasOwnProperty.call(e,c)&&(a[c]=e[c])}}
  function Gb(a){var b=arguments.length;if(1==b&&u(arguments[0]))return Gb.apply(null,arguments[0]);for(var c={},e=0;e<b;e++)c[arguments[e]]=!0;return c};function Hb(a){Hb[" "](a);return a}Hb[" "]=ca;function Ib(a,b){var c=Jb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Kb=Cb("Opera"),G=Cb("Trident")||Cb("MSIE"),Lb=Cb("Edge"),H=Cb("Gecko")&&!(-1!=zb.toLowerCase().indexOf("webkit")&&!Cb("Edge"))&&!(Cb("Trident")||Cb("MSIE"))&&!Cb("Edge"),I=-1!=zb.toLowerCase().indexOf("webkit")&&!Cb("Edge"),Mb=I&&Cb("Mobile"),Nb=Cb("Macintosh"),Ob=Cb("Android"),Pb=Cb("iPhone")&&!Cb("iPod")&&!Cb("iPad"),Qb=Cb("iPad");function Rb(){var a=g.document;return a?a.documentMode:void 0}var Sb;
  a:{var Tb="",Ub=function(){var a=zb;if(H)return/rv:([^\);]+)(\)|;)/.exec(a);if(Lb)return/Edge\/([\d\.]+)/.exec(a);if(G)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(I)return/WebKit\/(\S+)/.exec(a);if(Kb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ub&&(Tb=Ub?Ub[1]:"");if(G){var Vb=Rb();if(null!=Vb&&Vb>parseFloat(Tb)){Sb=String(Vb);break a}}Sb=Tb}var Jb={};
  function Wb(a){return Ib(a,function(){for(var b=0,c=kb(String(Sb)).split("."),e=kb(String(a)).split("."),f=Math.max(c.length,e.length),h=0;0==b&&h<f;h++){var k=c[h]||"",l=e[h]||"";do{k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];l=/(\d*)(\D*)(.*)/.exec(l)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=wb(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||wb(0==k[2].length,0==l[2].length)||wb(k[2],l[2]);k=k[3];l=l[3]}while(0==b)}return 0<=b})}var Xb;var Yb=g.document;
  Xb=Yb&&G?Rb()||("CSS1Compat"==Yb.compatMode?parseInt(Sb,10):5):void 0;var Zb=!G||9<=Number(Xb),$b=!H&&!G||G&&9<=Number(Xb)||H&&Wb("1.9.1"),ac=G&&!Wb("9");var bc={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};function cc(){this.eo="";this.Is=dc}cc.prototype.Se=!0;cc.prototype.Jd=function(){return this.eo};cc.prototype.toString=function(){return"Const{"+this.eo+"}"};function ec(a){return a instanceof cc&&a.constructor===cc&&a.Is===dc?a.eo:"type_error:Const"}var dc={};function fc(){this.mr="";this.Js=gc}fc.prototype.Se=!0;fc.prototype.Jd=function(){return this.mr};fc.prototype.Lm=!0;fc.prototype.Tg=function(){return 1};var gc={};function hc(){this.cg="";this.Gs=ic}hc.prototype.Se=!0;hc.prototype.Jd=function(){return this.cg};hc.prototype.Lm=!0;hc.prototype.Tg=function(){return 1};function jc(a){if(a instanceof hc&&a.constructor===hc&&a.Gs===ic)return a.cg;ea(a);return"type_error:SafeUrl"}var kc=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;function lc(a){if(a instanceof hc)return a;a=a.Se?a.Jd():String(a);kc.test(a)||(a="about:invalid#zClosurez");return mc(a)}var ic={};function mc(a){var b=new hc;b.cg=a;return b}mc("about:blank");function nc(){this.xn="";this.Fs=oc}nc.prototype.Se=!0;var oc={};nc.prototype.Jd=function(){return this.xn};nc.prototype.Ek=function(a){this.xn=a;return this};var pc=(new nc).Ek("");function qc(a){var b="",c;for(c in a){if(!/^[-_a-zA-Z0-9]+$/.test(c))throw Error("Name allows only [-_a-zA-Z0-9], got: "+c);var e=a[c];null!=e&&(e=u(e)?ta(e,rc).join(" "):rc(e),b+=c+":"+e+";")}return b?(new nc).Ek(b):pc}
  function rc(a){if(a instanceof hc)a='url("'+jc(a).replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';else if(a instanceof cc)a=ec(a);else{a=String(a);var b=a.replace(sc,"$1").replace(tc,"url");if(b=uc.test(b)){for(var c=b=!0,e=0;e<a.length;e++){var f=a.charAt(e);"'"==f&&c?b=!b:'"'==f&&b&&(c=!c)}b=b&&c}a=b?vc(a):"zClosurez"}return a}var uc=/^[-,."'%_!# a-zA-Z0-9]+$/,tc=/\b(url\([ \t\n]*)('[ -&(-\[\]-~]*'|"[ !#-\[\]-~]*"|[!#-&*-\[\]-~]*)([ \t\n]*\))/g,sc=/\b(hsl|hsla|rgb|rgba|matrix|(rotate|scale|translate)(X|Y|Z|3d)?)\([-0-9a-z.%, ]+\)/g;
  function vc(a){return a.replace(tc,function(a,c,e,f){var b="";e=e.replace(/^(['"])(.*)\1$/,function(a,c,e){b=c;return e});a=lc(e).Jd();return c+b+a+b+f})};function wc(){this.cg="";this.Es=xc;this.Pp=null}wc.prototype.Lm=!0;wc.prototype.Tg=function(){return this.Pp};wc.prototype.Se=!0;wc.prototype.Jd=function(){return this.cg};function yc(a){if(a instanceof wc&&a.constructor===wc&&a.Es===xc)return a.cg;ea(a);return"type_error:SafeHtml"}function zc(a){if(a instanceof wc)return a;var b=null;a.Lm&&(b=a.Tg());return Ac(lb(a.Se?a.Jd():String(a)),b)}
  var Bc=/^[a-zA-Z0-9-]+$/,Cc={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0},Dc={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,META:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};
  function Ec(a,b,c){var e=String(a);if(!Bc.test(e))throw Error("Invalid tag name <"+e+">.");if(e.toUpperCase()in Dc)throw Error("Tag name <"+e+"> is not allowed for SafeHtml.");a=String(a);e=null;var f="<"+a,h="";if(b)for(n in b){if(!Bc.test(n))throw Error('Invalid attribute name "'+n+'".');var k=b[n];if(null!=k){var l=a;var m=n;if(k instanceof cc)k=ec(k);else if("style"==m.toLowerCase()){if(!ha(k))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof k+
  " given: "+k);k instanceof nc||(k=qc(k));k instanceof nc&&k.constructor===nc&&k.Fs===oc?k=k.xn:(ea(k),k="type_error:SafeStyle")}else{if(/^on/i.test(m))throw Error('Attribute "'+m+'" requires goog.string.Const value, "'+k+'" given.');if(m.toLowerCase()in Cc)if(k instanceof fc)k instanceof fc&&k.constructor===fc&&k.Js===gc?k=k.mr:(ea(k),k="type_error:TrustedResourceUrl");else if(k instanceof hc)k=jc(k);else if(q(k))k=lc(k).Jd();else throw Error('Attribute "'+m+'" on tag "'+l+'" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+
  k+'" given.');}k.Se&&(k=k.Jd());m=m+'="'+lb(String(k))+'"';h+=" "+m}}var n=f+h;null!=c?u(c)||(c=[c]):c=[];!0===bc[a.toLowerCase()]?n+=">":(c=Fc(c),n+=">"+yc(c)+"</"+a+">",e=c.Tg());(b=b&&b.dir)&&(e=/^(ltr|rtl|auto)$/i.test(b)?0:null);return Ac(n,e)}function Fc(a){function b(a){u(a)?ra(a,b):(a=zc(a),e+=yc(a),a=a.Tg(),0==c?c=a:0!=a&&c!=a&&(c=null))}var c=0,e="";ra(arguments,b);return Ac(e,c)}var xc={};function Ac(a,b){return(new wc).Ek(a,b)}wc.prototype.Ek=function(a,b){this.cg=a;this.Pp=b;return this};
  Ac("<!DOCTYPE html>",0);var Gc=Ac("",0),Hc=Ac("<br>",0);function Ic(a,b){a.innerHTML=yc(b)};function Jc(a,b){this.width=a;this.height=b}d=Jc.prototype;d.clone=function(){return new Jc(this.width,this.height)};d.Ws=function(){return this.width*this.height};d.aspectRatio=function(){return this.width/this.height};d.zq=function(){return!this.Ws()};d.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};d.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
  d.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};d.scale=function(a,b){b=t(b)?b:a;this.width*=a;this.height*=b;return this};function Kc(a){return a?new Lc(Mc(a)):pa||(pa=new Lc)}
  function Nc(a,b){var c=document;b=b||c;if(b.querySelectorAll&&b.querySelector)return b.querySelectorAll("TBODY"+(a?"."+a:""));if(a&&b.getElementsByClassName){b=b.getElementsByClassName(a);c={};for(var e=0,f=0,h;h=b[f];f++)"TBODY"==h.nodeName&&(c[e++]=h);c.length=e;return c}b=b.getElementsByTagName("TBODY");if(a){c={};for(f=e=0;h=b[f];f++){var k=h.className;"function"==typeof k.split&&wa(k.split(/\s+/),a)&&(c[e++]=h)}c.length=e;return c}return b}
  function Oc(a,b){Db(b,function(b,e){b&&b.Se&&(b=b.Jd());"style"==e?a.style.cssText=b:"class"==e?a.className=b:"for"==e?a.htmlFor=b:Pc.hasOwnProperty(e)?a.setAttribute(Pc[e],b):hb(e,"aria-")||hb(e,"data-")?a.setAttribute(e,b):a[e]=b})}var Pc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
  function Qc(){var a=window.document;a="CSS1Compat"==a.compatMode?a.documentElement:a.body;return new Jc(a.clientWidth,a.clientHeight)}function Sc(a){var b=Tc(a);a=a.parentWindow||a.defaultView;return G&&Wb("10")&&a.pageYOffset!=b.scrollTop?new A(b.scrollLeft,b.scrollTop):new A(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)}function Tc(a){return a.scrollingElement?a.scrollingElement:I||"CSS1Compat"!=a.compatMode?a.body||a.documentElement:a.documentElement}
  function C(a,b,c){return Uc(document,arguments)}function Uc(a,b){var c=String(b[0]),e=b[1];if(!Zb&&e&&(e.name||e.type)){c=["<",c];e.name&&c.push(' name="',lb(e.name),'"');if(e.type){c.push(' type="',lb(e.type),'"');var f={};Fb(f,e);delete f.type;e=f}c.push(">");c=c.join("")}c=a.createElement(c);e&&(q(e)?c.className=e:u(e)?c.className=e.join(" "):Oc(c,e));2<b.length&&Vc(a,c,b,2);return c}
  function Vc(a,b,c,e){function f(c){c&&b.appendChild(q(c)?a.createTextNode(c):c)}for(;e<c.length;e++){var h=c[e];!fa(h)||ha(h)&&0<h.nodeType?f(h):ra(Wc(h)?za(h):h,f)}}function Xc(a){for(var b;b=a.firstChild;)a.removeChild(b)}function Yc(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)}function F(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}
  function Zc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function Mc(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
  function $c(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else Xc(a),a.appendChild(Mc(a).createTextNode(String(b)))}var ad={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},bd={IMG:" ",BR:"\n"};function cd(a){return G&&!Wb("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}
  function dd(a){a=a.tabIndex;return t(a)&&0<=a&&32768>a}function ed(a){if(ac&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];fd(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");ac||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}function gd(a){var b=[];fd(a,b,!1);return b.join("")}
  function fd(a,b,c){if(!(a.nodeName in ad))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in bd)b.push(bd[a.nodeName]);else for(a=a.firstChild;a;)fd(a,b,c),a=a.nextSibling}function Wc(a){if(a&&"number"==typeof a.length){if(ha(a))return"function"==typeof a.item||"string"==typeof a.item;if(x(a))return"function"==typeof a.item}return!1}function Lc(a){this.kd=a||g.document||document}d=Lc.prototype;d.Yb=Kc;
  d.F=function(a){return q(a)?this.kd.getElementById(a):a};d.getElementsByTagName=function(a,b){return(b||this.kd).getElementsByTagName(String(a))};d.setProperties=Oc;d.O=function(a,b,c){return Uc(this.kd,arguments)};d.createElement=function(a){return this.kd.createElement(String(a))};d.createTextNode=function(a){return this.kd.createTextNode(String(a))};
  d.sp=function(a,b){for(var c=this.kd,e=c.createElement("TABLE"),f=e.appendChild(c.createElement("TBODY")),h=0;h<a;h++){for(var k=c.createElement("TR"),l=0;l<b;l++)k.appendChild(c.createElement("TD"));f.appendChild(k)}return e};d.appendChild=function(a,b){a.appendChild(b)};d.append=function(a,b){Vc(Mc(a),a,arguments,1)};d.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
  d.vr=Xc;d.removeNode=F;d.je=function(a){return $b&&void 0!=a.children?a.children:sa(a.childNodes,function(a){return 1==a.nodeType})};d.contains=Zc;d.pe=function(a){var b;(b="A"==a.tagName||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!cd(a)||dd(a)):cd(a)&&dd(a))&&G?(a=!x(a.getBoundingClientRect)||G&&null==a.parentElement?{height:a.offsetHeight,width:a.offsetWidth}:a.getBoundingClientRect(),a=null!=a&&0<a.height&&0<a.width):a=b;return a};
  function hd(a,b){this.w=a;this.type=b;a.o.Zl&&(this.Wc=a.o.Zl[b],this.Vj=a.o.Zl[B.Eg[b]],this.Jm=!this.Wc)}d=hd.prototype;d.zb=null;d.$d=null;d.Rd=null;d.yc=0;d.Fa=0;d.Te=!1;d.Wc=null;d.Vj=null;d.Jm=null;
  d.Rj=function(a){var b=this,c=b.w,e=a.w;a.isConnected()&&a.disconnect();if(b.isConnected()){var f=D(b),h=b.Rd;b.Rd=null;if(f.Wa)h=B.D.Ke(f),f.v(),f=null;else if(b.type==B.ab){if(!f.S)throw"Orphan block does not have an output connection.";var k=id(e,f);k&&(f.S.connect(k),f=null)}else if(b.type==B.Ka){if(!f.X)throw"Orphan block does not have a previous connection.";for(k=e;k.R;){var l=Ya(k);if(l&&!l.Wa)k=l;else{jd(f.X,k.R)&&(k.R.connect(f.X),f=null);break}}}if(f&&(b.disconnect(),B.i.Rb)){var m=B.i.$b();
  setTimeout(function(){f.o&&!f.getParent()&&(B.i.T(m),f.S?kd(f.S,b):f.X&&kd(f.X,b),B.i.T(!1))},B.yj)}b.Rd=h}var n;B.i.isEnabled()&&(n=new B.i.Jh(e));ld(b,a);e.kg(c);n&&(n.te(),B.i.M(n))};d.v=function(){if(this.isConnected())throw"Disconnect connection before disposing of it.";this.Te&&md(this.Wc,this);this.Vj=this.Wc=null};function nd(a){return a.type==B.ab||a.type==B.Ka}d.isConnected=function(){return!!this.zb};
  function od(a,b){if(!b)return 3;if(nd(a))var c=a.w,e=b.w;else e=a.w,c=b.w;return c&&c==e?1:b.type!=B.Eg[a.type]?2:c&&e&&c.o!==e.o?5:jd(a,b)?c.Wa&&!e.Wa?6:0:4}d.Fk=function(a){if(0!=od(this,a))return!1;if(a.type==B.Fg||a.type==B.Ge)if(a.isConnected()||this.isConnected())return!1;return a.type==B.ab&&a.isConnected()&&!D(a).Md()&&!D(a).Wa||this.type==B.Ge&&a.isConnected()&&!this.w.R&&!D(a).Wa&&D(a).R||-1!=B.dk.indexOf(a)?!1:!0};
  d.connect=function(a){if(this.zb!=a){switch(od(this,a)){case 0:break;case 1:throw"Attempted to connect a block to itself.";case 5:throw"Blocks not on same workspace.";case 2:throw"Attempt to connect incompatible types.";case 3:throw"Target connection is null.";case 4:throw"Connection checks failed. "+(this+" expected "+this.$d+", found "+a.$d);case 6:throw"Connecting non-shadow to shadow block.";default:throw"Unknown connection failure: this should never happen!";}nd(this)?this.Rj(a):a.Rj(this)}};
  function ld(a,b){a.zb=b;b.zb=a}function pd(a,b){for(var c=!1,e=0;e<a.W.length;e++){var f=a.W[e].connection;if(f&&f.type==B.ab&&jd(b.S,f)){if(c)return null;c=f}}return c}function id(a,b){for(var c;c=pd(a,b);)if(a=D(c),!a||a.Wa)return c;return null}d.disconnect=function(){var a=this.zb;if(nd(this)){var b=this.w;var c=a.w;a=this}else b=a.w,c=this.w;this.lm(b,c);a.Gn()};d.lm=function(a,b){var c;B.i.isEnabled()&&(c=new B.i.Jh(b));this.zb=this.zb.zb=null;b.kg(null);c&&(c.te(),B.i.M(c))};
  d.Gn=function(){var a=this.w,b=this.Rd;if(a.o&&b&&B.i.Rb)if(a=B.D.Ng(b,a.o),a.S)this.connect(a.S);else if(a.X)this.connect(a.X);else throw"Child block does not have output or previous statement.";};function D(a){return a.isConnected()?a.zb.w:null}function jd(a,b){if(!a.$d||!b.$d)return!0;for(var c=0;c<a.$d.length;c++)if(-1!=b.$d.indexOf(a.$d[c]))return!0;return!1}d.Vq=function(){this.isConnected()&&!jd(this,this.zb)&&eb(nd(this)?D(this):this.w)};
  d.vh=function(a){a?(u(a)||(a=[a]),this.$d=a,this.Vq()):this.$d=null};d.Pq=function(){return[]};
  d.toString=function(){var a=this.w;if(a)if(a.S==this)var b="Output Connection of ";else if(a.X==this)b="Previous Connection of ";else if(a.R==this)b="Next Connection of ";else if(b=va(a.W,function(a){return a.connection==this},this))b='Input "'+b.name+'" connection on ';else return console.warn("Connection not actually connected to sourceBlock_"),"Orphan Connection";else return"Orphan Connection";return b+qd(a)};function rd(a,b){rd.m.constructor.call(this,a,b);this.$k=new A(0,0)}y(rd,hd);function sd(a,b){var c=a.yc-b.yc;a=a.Fa-b.Fa;return Math.sqrt(c*c+a*a)}function kd(a,b){if(!a.w.o.lb()){var c=td(a.w);if(!c.rc){var e=!1;if(!c.Md()){c=td(b.w);if(!c.Md())return;b=a;e=!0}var f=B.selected==c;f||c.Hg();var h=b.yc+B.zc-a.yc;a=b.Fa+B.zc-a.Fa;e&&(a=-a);c.s&&(h=-h);c.moveBy(h,a);f||c.eg()}}}d=rd.prototype;d.moveTo=function(a,b){this.Te&&md(this.Wc,this);this.yc=a;this.Fa=b;this.Jm||ud(this.Wc,this)};
  d.moveBy=function(a,b){this.moveTo(this.yc+a,this.Fa+b)};function vd(a,b){a.moveTo(b.x+a.$k.x,b.y+a.$k.y)}function wd(a,b,c){a.$k.x=b;a.$k.y=c}function xd(a){var b=a.zb.yc-a.yc,c=a.zb.Fa-a.Fa;if(0!=b||0!=c){a=D(a);var e=a.N();if(!e)throw"block is not rendered.";e=B.h.ac(e);a.N().setAttribute("transform","translate("+(e.x-b)+","+(e.y-c)+")");yd(a,-b,-c)}}
  d.closest=function(a,b){var c=this.Vj;if(c.length){var e=this.Fa,f=this.yc;this.yc=f+b.x;this.Fa=e+b.y;var h=zd(c,this);b=null;for(var k=a,l,m=h-1;0<=m&&Math.abs(c[m].Fa-this.Fa)<=a;)l=c[m],this.Fk(l,k)&&(b=l,k=sd(l,this)),m--;for(;h<c.length&&Math.abs(c[h].Fa-this.Fa)<=a;)l=c[h],this.Fk(l,k)&&(b=l,k=sd(l,this)),h++;this.yc=f;this.Fa=e;a={connection:b,rr:k}}else a={connection:null,rr:a};return a};
  d.Ck=function(){var a=this.type==B.ab||this.type==B.Fg?"m 0,0 "+Ad+" v 5":"m -20,0 h 5 l 6,4 3,0 6,-4 h 5";var b=this.w.ka();hd.tq=B.h.A("path",{"class":"blocklyHighlightedConnectionPath",d:a,transform:"translate("+(this.yc-b.x)+","+(this.Fa-b.y)+")"+(this.w.s?" scale(-1 1)":"")},this.w.N())};
  function Bd(a){Cd(a,!1);var b=[];if(a.type!=B.ab&&a.type!=B.Ka)return b;if(a=D(a)){if(a.isCollapsed()){var c=[];a.S&&c.push(a.S);a.R&&c.push(a.R);a.X&&c.push(a.X)}else c=a.Fd(!0);for(var e=0;e<c.length;e++)b.push.apply(b,Bd(c[e]));b.length||(b[0]=a)}return b}function Dd(){F(hd.tq);delete hd.tq}function Cd(a,b){(a.Jm=b)&&a.Te?md(a.Wc,a):b||a.Te||ud(a.Wc,a)}d.Fk=function(a,b){return sd(this,a)>b?!1:rd.m.Fk.call(this,a)};d.lm=function(a,b){rd.m.lm.call(this,a,b);a.P&&a.Y();b.P&&(Ed(b),b.Y())};
  d.Gn=function(){var a=this.w,b=this.Rd;if(a.o&&b&&B.i.Rb){rd.m.Gn.call(this);b=D(this);if(!b)throw"Couldn't respawn the shadow block that should exist here.";b.Ue();b.Y(!1);a.P&&a.Y()}};d.Pq=function(a){return Fd(this.Vj,this,a)};d.Rj=function(a){rd.m.Rj.call(this,a);var b=this.w;a=a.w;b.P&&Ed(b);a.P&&Ed(a);b.P&&a.P&&(this.type==B.Ka||this.type==B.Ge?a.Y():b.Y())};d.Vq=function(){this.isConnected()&&!jd(this,this.zb)&&(eb(nd(this)?D(this):this.w),this.w.Vb())}
    function Hd(a){this.sf=B.selected=a;this.j=a.o;a=this.sf.Fd(!1);var b;a:{for(b=this.sf.R;b;){var c=D(b);if(!c)break a;b=c.R}b=null}b&&b!=this.sf.R&&a.push(b);this.Ql=a;this.hh=this.Mb=null;this.yn=0;this.yf=!1}Hd.prototype.v=function(){this.j=this.sf=null;this.Ql.length=0;this.hh=this.Mb=null};
    Hd.prototype.update=function(a,b){var c=this.Mb,e=this.Mb;this.hh=this.Mb=null;this.yn=B.zc;for(var f=0;f<this.Ql.length;f++){var h=this.Ql[f],k=h.closest(this.yn,a);k.connection&&(this.Mb=k.connection,this.hh=h,this.yn=k.rr)}(a=e!=this.Mb)&&c&&Dd();c=!!this.Mb&&b!=B.uo;this.yf=(b=!!b&&!this.sf.getParent()&&this.sf.Ob())&&!c;b&&this.Mb&&(Dd(),this.Mb=null);!this.yf&&a&&this.Mb&&this.Mb&&this.Mb.Ck()};function Id(a,b){this.Qa=a;this.j=b;this.Og=new Hd(this.Qa);this.Gf=null;this.yf=!1;this.Sd=this.Qa.ka();b=[];a=Ja(a,!1);for(var c=0,e;e=a[c];c++){e=Jd(e);for(var f=0;f<e.length;f++)b.push({location:e[f].ah,icon:e[f]})}this.ck=b}Id.prototype.v=function(){this.Ra=this.j=this.Qa=null;this.ck.length=0;this.Og&&(this.Og.v(),this.Og=null)};
    function Kd(a,b,c){c=a.nh(c);a.Qa.Vk(Ha(a.Sd,c));for(var e=0;e<a.ck.length;e++){var f=a.ck[e];Ld(f.icon,Ha(f.location,c))}a.Gf=Md(a.j,b);a.Og.update(c,a.Gf);a.yf=a.Og.yf;b=a.j.wc;a.yf?(a.Qa.ej(!0),a.Gf==B.Fl&&b&&Nd(b,!0)):(a.Qa.ej(!1),b&&Nd(b,!1))}
    function Od(a,b,c){Kd(a,b,c);a.ck=[];B.ya.nm();b=a.nh(c);a.Qa.Mq(Ha(a.Sd,b));c=a.j.wc;a.yf?(c&&Pd(c.close,100,c),a.ji(),a.Qa.v(!1,!0)):c&&c.close();a.yf||(yd(a.Qa,b.x,b.y),a.Qa.mf(!1),b=a.Og,b.Mb&&(b.hh.connect(b.Mb),b.sf.P&&(B.ya.vt((nd(b.hh)?b.Mb:b.hh).w),Qd(td(b.sf))),b.Mb&&Dd()),a.Qa.Y(),a.ji(),Rd(a.Qa));a.j.xb(!0);(b=a.j.V)&&B.h.wb(b.jc,a.Qa.Ob()?"blocklyToolboxDelete":"blocklyToolboxGrab");B.i.T(!1)}Id.prototype.ji=function(){var a=new B.i.Jh(this.Qa);a.dn=this.Sd;a.te();B.i.M(a)};
    Id.prototype.nh=function(a){a=new A(a.x/this.j.scale,a.y/this.j.scale);this.j.Mi&&(a=a.scale(1/this.j.options.Gc.scale));return a};var Sd=!G||9<=Number(Xb),Td=!G||9<=Number(Xb),Ud=G&&!Wb("9"),Vd="ontouchstart"in g||!!(g.document&&document.documentElement&&"ontouchstart"in document.documentElement)||!(!g.navigator||!g.navigator.maxTouchPoints&&!g.navigator.msMaxTouchPoints),Wd="PointerEvent"in g,Xd="MSPointerEvent"in g&&!(!g.navigator||!g.navigator.msPointerEnabled),Yd=function(){if(!g.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});g.addEventListener("test",
    ca,b);g.removeEventListener("test",ca,b);return a}();function Zd(){0!=$d&&(ae[ia(this)]=this);this.Mg=this.Mg;this.re=this.re}var $d=0,ae={};Zd.prototype.Mg=!1;Zd.prototype.v=function(){if(!this.Mg&&(this.Mg=!0,this.Ia(),0!=$d)){var a=ia(this);if(0!=$d&&this.re&&0<this.re.length)throw Error(this+" did not empty its onDisposeCallbacks queue. This probably means it overrode dispose() or disposeInternal() without calling the superclass' method.");delete ae[a]}};
    function be(a,b){a.Mg?aa(void 0)?b.call(void 0):b():(a.re||(a.re=[]),a.re.push(aa(void 0)?na(b,void 0):b))}Zd.prototype.Ia=function(){if(this.re)for(;this.re.length;)this.re.shift()()};function ce(a){a&&"function"==typeof a.v&&a.v()};function de(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.dg=!1;this.xr=!0}de.prototype.stopPropagation=function(){this.dg=!0};de.prototype.preventDefault=function(){this.defaultPrevented=!0;this.xr=!1};function ee(a){return I?"webkit"+a:Kb?"o"+a.toLowerCase():a.toLowerCase()}
    var fe={Bw:"click",jz:"rightclick",Lw:"dblclick",Cg:"mousedown",Dg:"mouseup",Nh:"mouseover",Mh:"mouseout",As:"mousemove",ys:"mouseenter",zs:"mouseleave",Bg:"mousecancel",oz:"selectionchange",pz:"selectstart",Rz:"wheel",Dx:"keypress",Cx:"keydown",Ex:"keyup",yw:"blur",tx:"focus",Mw:"deactivate",ux:"focusin",vx:"focusout",zg:"change",gz:"reset",nz:"select",yz:"submit",Ax:"input",cz:"propertychange",ex:"dragstart",Yw:"drag",$w:"dragenter",bx:"dragover",ax:"dragleave",kx:"drop",Zw:"dragend",Gz:"touchstart",
    Fz:"touchmove",Ez:"touchend",Dz:"touchcancel",tw:"beforeunload",Gw:"consolemessage",Hw:"contextmenu",Nw:"devicechange",Ow:"devicemotion",Pw:"deviceorientation",Sw:"DOMContentLoaded",px:"error",zx:"help",Fx:"load",Nx:"losecapture",Ny:"orientationchange",ez:"readystatechange",hz:"resize",kz:"scroll",Iz:"unload",zw:"canplay",Aw:"canplaythrough",mx:"durationchange",nx:"emptied",ox:"ended",Ix:"loadeddata",Jx:"loadedmetadata",Ry:"pause",Sy:"play",Ty:"playing",dz:"ratechange",lz:"seeked",mz:"seeking",vz:"stalled",
    zz:"suspend",Cz:"timeupdate",Pz:"volumechange",Qz:"waiting",uz:"sourceopen",sz:"sourceended",rz:"sourceclosed",fw:"abort",Kz:"update",Nz:"updatestart",Lz:"updateend",yx:"hashchange",Oy:"pagehide",Py:"pageshow",bz:"popstate",Jw:"copy",Qy:"paste",Kw:"cut",nw:"beforecopy",ow:"beforecut",rw:"beforepaste",ly:"online",ky:"offline",Px:"message",Fw:"connect",Bx:"install",gw:"activate",sx:"fetch",wx:"foreignfetch",Qx:"messageerror",wz:"statechange",Mz:"updatefound",Iw:"controllerchange",lw:ee("AnimationStart"),
    jw:ee("AnimationEnd"),kw:ee("AnimationIteration"),Hz:ee("TransitionEnd"),Vy:"pointerdown",az:"pointerup",Uy:"pointercancel",Yy:"pointermove",$y:"pointerover",Zy:"pointerout",Wy:"pointerenter",Xy:"pointerleave",xx:"gotpointercapture",Ox:"lostpointercapture",Rx:"MSGestureChange",Sx:"MSGestureEnd",Tx:"MSGestureHold",Ux:"MSGestureStart",Vx:"MSGestureTap",Wx:"MSGotPointerCapture",Xx:"MSInertiaStart",Yx:"MSLostPointerCapture",Zx:"MSPointerCancel",$x:"MSPointerDown",ay:"MSPointerEnter",by:"MSPointerHover",
    ey:"MSPointerLeave",gy:"MSPointerMove",hy:"MSPointerOut",iy:"MSPointerOver",jy:"MSPointerUp",Az:"text",Bz:G?"textinput":"textInput",Dw:"compositionstart",Ew:"compositionupdate",Cw:"compositionend",pw:"beforeinput",qx:"exit",Gx:"loadabort",Hx:"loadcommit",Kx:"loadredirect",Lx:"loadstart",Mx:"loadstop",iz:"responsive",qz:"sizechanged",Jz:"unresponsive",Oz:"visibilitychange",xz:"storage",Xw:"DOMSubtreeModified",Tw:"DOMNodeInserted",Vw:"DOMNodeRemoved",Ww:"DOMNodeRemovedFromDocument",Uw:"DOMNodeInsertedIntoDocument",
    Qw:"DOMAttrModified",Rw:"DOMCharacterDataModified",sw:"beforeprint",iw:"afterprint",qw:"beforeinstallprompt",mw:"appinstalled"},ge={Cg:Wd?"pointerdown":Xd?"MSPointerDown":"mousedown",Dg:Wd?"pointerup":Xd?"MSPointerUp":"mouseup",Bg:Wd?"pointercancel":Xd?"MSPointerCancel":"mousecancel",As:Wd?"pointermove":Xd?"MSPointerMove":"mousemove",Nh:Wd?"pointerover":Xd?"MSPointerOver":"mouseover",Mh:Wd?"pointerout":Xd?"MSPointerOut":"mouseout",ys:Wd?"pointerenter":Xd?"MSPointerEnter":"mouseenter",zs:Wd?"pointerleave":
    Xd?"MSPointerLeave":"mouseleave"};function he(a,b){de.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.rn=!1;this.pointerId=0;this.pointerType="";this.Cd=null;a&&this.$(a,b)}y(he,de);var ie=[1,4,2],je={2:"touch",3:"pen",4:"mouse"};
    he.prototype.$=function(a,b){var c=this.type=a.type,e=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(H){a:{try{Hb(b.nodeName);var f=!0;break a}catch(h){}f=!1}f||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;null===e?(this.offsetX=I||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=I||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,
    this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==e.clientX?e.clientX:e.pageX,this.clientY=void 0!==e.clientY?e.clientY:e.pageY,this.screenX=e.screenX||0,this.screenY=e.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.rn=Nb?a.metaKey:a.ctrlKey;this.pointerId=
    a.pointerId||0;this.pointerType=q(a.pointerType)?a.pointerType:je[a.pointerType]||"";this.state=a.state;this.Cd=a;a.defaultPrevented&&this.preventDefault()};function ke(a){return Sd?0==a.Cd.button:"click"==a.type?!0:!!(a.Cd.button&ie[0])}he.prototype.stopPropagation=function(){he.m.stopPropagation.call(this);this.Cd.stopPropagation?this.Cd.stopPropagation():this.Cd.cancelBubble=!0};
    he.prototype.preventDefault=function(){he.m.preventDefault.call(this);var a=this.Cd;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Ud)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var le="closure_listenable_"+(1E6*Math.random()|0);function me(a){return!(!a||!a[le])}var ne=0;function oe(a,b,c,e,f){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!e;this.Bk=f;this.key=++ne;this.sh=this.Kj=!1}function pe(a){a.sh=!0;a.listener=null;a.proxy=null;a.src=null;a.Bk=null};function qe(a){this.src=a;this.dc={};this.qj=0}qe.prototype.add=function(a,b,c,e,f){var h=a.toString();a=this.dc[h];a||(a=this.dc[h]=[],this.qj++);var k=re(a,b,e,f);-1<k?(b=a[k],c||(b.Kj=!1)):(b=new oe(b,this.src,h,!!e,f),b.Kj=c,a.push(b));return b};qe.prototype.remove=function(a,b,c,e){a=a.toString();if(!(a in this.dc))return!1;var f=this.dc[a];b=re(f,b,c,e);return-1<b?(pe(f[b]),Array.prototype.splice.call(f,b,1),0==f.length&&(delete this.dc[a],this.qj--),!0):!1};
    function se(a,b){var c=b.type;c in a.dc&&xa(a.dc[c],b)&&(pe(b),0==a.dc[c].length&&(delete a.dc[c],a.qj--))}qe.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.dc)if(!a||c==a){for(var e=this.dc[c],f=0;f<e.length;f++)++b,pe(e[f]);delete this.dc[c];this.qj--}return b};qe.prototype.oi=function(a,b,c,e){a=this.dc[a.toString()];var f=-1;a&&(f=re(a,b,c,e));return-1<f?a[f]:null};
    function re(a,b,c,e){for(var f=0;f<a.length;++f){var h=a[f];if(!h.sh&&h.listener==b&&h.capture==!!c&&h.Bk==e)return f}return-1};var te="closure_lm_"+(1E6*Math.random()|0),ue={},ve=0;function we(a,b,c,e,f){if(e&&e.once)return xe(a,b,c,e,f);if(u(b)){for(var h=0;h<b.length;h++)we(a,b[h],c,e,f);return null}c=ye(c);return me(a)?a.ha(b,c,ha(e)?!!e.capture:!!e,f):ze(a,b,c,!1,e,f)}
    function ze(a,b,c,e,f,h){if(!b)throw Error("Invalid event type");var k=ha(f)?!!f.capture:!!f,l=Ae(a);l||(a[te]=l=new qe(a));c=l.add(b,c,e,k,h);if(c.proxy)return c;e=Be();c.proxy=e;e.src=a;e.listener=c;if(a.addEventListener)Yd||(f=k),void 0===f&&(f=!1),a.addEventListener(b.toString(),e,f);else if(a.attachEvent)a.attachEvent(Ce(b.toString()),e);else if(a.addListener&&a.removeListener)a.addListener(e);else throw Error("addEventListener and attachEvent are unavailable.");ve++;return c}
    function Be(){var a=De,b=Td?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function xe(a,b,c,e,f){if(u(b)){for(var h=0;h<b.length;h++)xe(a,b[h],c,e,f);return null}c=ye(c);return me(a)?a.Fq(b,c,ha(e)?!!e.capture:!!e,f):ze(a,b,c,!0,e,f)}function Ee(a,b,c,e,f){if(u(b))for(var h=0;h<b.length;h++)Ee(a,b[h],c,e,f);else e=ha(e)?!!e.capture:!!e,c=ye(c),me(a)?a.Nc(b,c,e,f):a&&(a=Ae(a))&&(b=a.oi(b,c,e,f))&&Fe(b)}
    function Fe(a){if(!t(a)&&a&&!a.sh){var b=a.src;if(me(b))se(b.ge,a);else{var c=a.type,e=a.proxy;b.removeEventListener?b.removeEventListener(c,e,a.capture):b.detachEvent?b.detachEvent(Ce(c),e):b.addListener&&b.removeListener&&b.removeListener(e);ve--;(c=Ae(b))?(se(c,a),0==c.qj&&(c.src=null,b[te]=null)):pe(a)}}}function Ce(a){return a in ue?ue[a]:ue[a]="on"+a}
    function Ge(a,b,c,e){var f=!0;if(a=Ae(a))if(b=a.dc[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var h=b[a];h&&h.capture==c&&!h.sh&&(h=He(h,e),f=f&&!1!==h)}return f}function He(a,b){var c=a.listener,e=a.Bk||a.src;a.Kj&&Fe(a);return c.call(e,b)}
    function De(a,b){if(a.sh)return!0;if(!Td){if(!b)a:{b=["window","event"];for(var c=g,e=0;e<b.length;e++)if(c=c[b[e]],null==c){b=null;break a}b=c}e=b;b=new he(e,this);c=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(k){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=b.currentTarget;f;f=f.parentNode)e.push(f);a=a.type;for(f=e.length-1;!b.dg&&0<=f;f--){b.currentTarget=e[f];var h=Ge(e[f],a,!0,b);c=c&&h}for(f=0;!b.dg&&f<e.length;f++)b.currentTarget=
    e[f],h=Ge(e[f],a,!1,b),c=c&&h}return c}return He(a,new he(b,this))}function Ae(a){a=a[te];return a instanceof qe?a:null}var Ie="__closure_events_fn_"+(1E9*Math.random()>>>0);function ye(a){if(x(a))return a;a[Ie]||(a[Ie]=function(b){return a.handleEvent(b)});return a[Ie]};B.Touch={};B.Touch.oj=null;B.Touch.xd={};g.PointerEvent?B.Touch.xd={mousedown:["pointerdown"],mouseenter:["pointerenter"],mouseleave:["pointerleave"],mousemove:["pointermove"],mouseout:["pointerout"],mouseover:["pointerover"],mouseup:["pointerup","pointercancel"],touchend:["pointerup"],touchcancel:["pointercancel"]}:Vd&&(B.Touch.xd={mousedown:["touchstart"],mousemove:["touchmove"],mouseup:["touchend","touchcancel"]});B.Pk=0;
    B.Xu=function(a,b){B.af();a.changedTouches&&1!=a.changedTouches.length||(B.Pk=setTimeout(function(){a.changedTouches&&(a.button=2,a.clientX=a.changedTouches[0].clientX,a.clientY=a.changedTouches[0].clientY);b&&Je(b,a)},B.ws))};B.af=function(){B.Pk&&(clearTimeout(B.Pk),B.Pk=0)};B.Touch.ee=function(){B.Touch.oj=null};B.Touch.Zn=function(a){return!B.Touch.Nu(a)||B.Touch.mt(a)};
    B.Touch.xk=function(a){return void 0!=a.pointerId?a.pointerId:a.changedTouches&&a.changedTouches[0]&&void 0!=a.changedTouches[0].identifier&&null!=a.changedTouches[0].identifier?a.changedTouches[0].identifier:"mouse"};B.Touch.mt=function(a){var b=B.Touch.xk(a);return void 0!=B.Touch.oj&&null!=B.Touch.oj?B.Touch.oj==b:"mousedown"==a.type||"touchstart"==a.type||"pointerdown"==a.type?(B.Touch.oj=b,!0):!1};
    B.Touch.Iv=function(a){if(hb(a.type,"touch")){var b=a.changedTouches[0];a.clientX=b.clientX;a.clientY=b.clientY}};B.Touch.Nu=function(a){return hb(a.type,"touch")||hb(a.type,"mouse")||hb(a.type,"pointer")};B.Touch.Lk=function(a){return hb(a.type,"touch")||hb(a.type,"pointer")};
    B.Touch.Lv=function(a){var b=[];if(a.changedTouches)for(var c=0;c<a.changedTouches.length;c++)b[c]={type:a.type,changedTouches:[a.changedTouches[c]],target:a.target,stopPropagation:function(){a.stopPropagation()},preventDefault:function(){a.preventDefault()}};else b.push(a);return b};function Ke(a){Ke.m.constructor.call(this);this.wf=a.ga();this.hc=a.o.id}y(Ke,Za);Ke.prototype.ua=function(){var a=Ke.m.ua.call(this);a.varId=this.wf;return a};Ke.prototype.Z=function(a){Ke.m.ua.call(this);this.wf=a.varId};function Oa(a){a&&(Oa.m.constructor.call(this,a),this.wg=a.type,this.vg=a.name)}y(Oa,Ke);Oa.prototype.type=B.i.Lo;Oa.prototype.ua=function(){var a=Oa.m.ua.call(this);a.varType=this.wg;a.varName=this.vg;return a};
    Oa.prototype.Z=function(a){Oa.m.Z.call(this,a);this.wg=a.varType;this.vg=a.varName};Oa.prototype.run=function(a){var b=$a(this);a?b.Vc(this.vg,this.wg,this.wf):b.Hf(this.wf)};function Qa(a){a&&(Qa.m.constructor.call(this,a),this.wg=a.type,this.vg=a.name)}y(Qa,Ke);Qa.prototype.type=B.i.Mo;Qa.prototype.ua=function(){var a=Qa.m.ua.call(this);a.varType=this.wg;a.varName=this.vg;return a};Qa.prototype.Z=function(a){Qa.m.Z.call(this,a);this.wg=a.varType;this.vg=a.varName};
    Qa.prototype.run=function(a){var b=$a(this);a?b.Hf(this.wf):b.Vc(this.vg,this.wg,this.wf)};function Ra(a,b){a&&(Ra.m.constructor.call(this,a),this.gn=a.name,this.cn=b)}y(Ra,Ke);Ra.prototype.type=B.i.No;Ra.prototype.ua=function(){var a=Ra.m.ua.call(this);a.oldName=this.gn;a.newName=this.cn;return a};Ra.prototype.Z=function(a){Ra.m.Z.call(this,a);this.gn=a.oldName;this.cn=a.newName};Ra.prototype.run=function(a){var b=$a(this);a?b.fg(this.wf,this.cn):b.fg(this.wf,this.gn)};function Le(a){this.na={};this.o=a}d=Le.prototype;d.clear=function(){this.na=Object(null)};d.Bn=function(a,b){var c=this.md(b,a.type),e=Me(this.o);B.i.T(!0);try{if(c&&c.ga()!=a.ga()){var f=a.type;b!=c.name&&Ne(c,b,e);for(b=0;b<e.length;b++)for(var h=void 0,k=e[b],l=a.ga(),m=c.ga(),n=0;h=k.W[n];n++)for(var p=0,r;r=h.Na[p];p++)r.qh()&&l==r.getValue()&&r.setValue(m);B.i.M(new Qa(a));this.na[f].splice(this.ti(f).indexOf(a),1)}else Ne(a,b,e)}finally{B.i.T(!1)}};
    d.fg=function(a,b){var c=this.me(a);if(!c)throw Error("Tried to rename a variable that didn't exist. ID: "+a);this.Bn(c,b)};function Ne(a,b,c){B.i.M(new Ra(a,b));a.name=b;for(b=0;b<c.length;b++)for(var e,f=c[b],h=a,k=0;e=f.W[k];k++)for(var l=0,m;m=e.Na[l];l++)m.qh()&&h.ga()==m.getValue()&&m.yb(h.name)}
    d.Vc=function(a,b,c){var e=this.md(a,b);if(e){if(c&&e.ga()!=c)throw Error('Variable "'+a+'" is already in use and its id is "'+e.ga()+'" which conflicts with the passed in id, "'+c+'".');return e}if(c&&this.me(c))throw Error('Variable id, "'+c+'", is already in use.');c=c||B.h.Ed();b=b||"";e=new Oe(this.o,a,b,c);this.na[b]?this.na[b].push(e):this.na[b]=[e];return e};
    d.Hf=function(a){var b=this.me(a);if(b){var c=b.name,e=this.Cm(a);a=0;for(var f;f=e[a];a++)if("procedures_defnoreturn"==f.type||"procedures_defreturn"==f.type){a=Pe(f,"NAME");c=B.g.CANNOT_DELETE_VARIABLE_PROCEDURE.replace("%1",c).replace("%2",a);B.alert(c);return}var h=this;1<e.length?(c=B.g.DELETE_VARIABLE_CONFIRMATION.replace("%1",String(e.length)).replace("%2",c),B.confirm(c,function(a){a&&h.Yj(b,e)})):h.Yj(b,e)}else console.warn("Can't delete non-existent variable: "+a)};
    d.Yj=function(a,b){var c=B.i.$b();c||B.i.T(!0);try{for(var e=0;e<b.length;e++)b[e].v(!0,!1);var f=this.na[a.type];b=0;for(var h;h=f[b];b++)if(h.ga()==a.ga()){f.splice(b,1);B.i.M(new Qa(a));break}}finally{c||B.i.T(!1)}};d.md=function(a,b){if(b=this.na[b||""])for(var c=0,e;e=b[c];c++)if(e.name.toLowerCase()==a.toLowerCase())return e;return null};d.me=function(a){for(var b=Object.keys(this.na),c=0;c<b.length;c++)for(var e=b[c],f=0,h;h=this.na[e][f];f++)if(h.ga()==a)return h;return null};
    d.ti=function(a){return(a=this.na[a||""])?a.slice():[]};d.Bm=function(){for(var a=Object.keys(this.na),b=!1,c=0;c<a.length;c++)""==a[c]&&(b=!0);b||a.push("");return a};d.ie=function(){for(var a=[],b=Object.keys(this.na),c=0;c<b.length;c++)a=a.concat(this.na[b[c]]);return a};d.Cm=function(a){for(var b=[],c=Me(this.o),e=0;e<c.length;e++){var f=Qe(c[e]);if(f)for(var h=0;h<f.length;h++)f[h].ga()==a&&b.push(c[e])}return b};function Re(a){this.jd=a.id;this.hc=a.o.id;this.group=B.i.yk;this.Rb=B.i.Rb}y(Re,Za);Re.prototype.ua=function(){var a={type:this.type};this.group&&(a.group=this.group);this.jd&&(a.commentId=this.jd);return a};Re.prototype.Z=function(a){this.jd=a.commentId;this.group=a.group};function Ua(a,b,c){a&&(Ua.m.constructor.call(this,a),this.Rq=b,this.Xk=c)}y(Ua,Re);d=Ua.prototype;d.type=B.i.po;d.ua=function(){var a=Ua.m.ua.call(this);a.newContents=this.Xk;return a};
    d.Z=function(a){Ua.m.Z.call(this,a);this.Xk=a.newValue};d.dh=function(){return this.Rq==this.Xk};d.run=function(a){var b=Se($a(this),this.jd);b?b.cd(a?this.Xk:this.Rq):console.warn("Can't change non-existent comment: "+this.jd)};function Ta(a){a&&(Ta.m.constructor.call(this,a),this.xml=a.nj())}y(Ta,Re);Ta.prototype.type=B.i.qo;Ta.prototype.ua=function(){var a=Ta.m.ua.call(this);a.xml=B.D.pc(this.xml);return a};Ta.prototype.Z=function(a){Ta.m.Z.call(this,a);this.xml=B.D.Kc("<xml>"+a.xml+"</xml>").firstChild};
    Ta.prototype.run=function(a){var b=$a(this);a?(a=C("xml"),a.appendChild(this.xml),B.D.fe(a,b)):(b=Se(b,this.jd))?b.v(!1,!1):console.warn("Can't uncreate non-existent comment: "+this.jd)};function Wa(a){a&&(Wa.m.constructor.call(this,a),this.xml=a.nj())}y(Wa,Re);Wa.prototype.type=B.i.ro;Wa.prototype.ua=function(){return Wa.m.ua.call(this)};Wa.prototype.Z=function(a){Wa.m.Z.call(this,a)};
    Wa.prototype.run=function(a){var b=$a(this);a?(b=Se(b,this.jd))?b.v(!1,!1):console.warn("Can't uncreate non-existent comment: "+this.jd):(a=C("xml"),a.appendChild(this.xml),B.D.fe(a,b))};function Va(a){a&&(Va.m.constructor.call(this,a),this.Yl=a,this.fn=a.Pc.clone(),this.Xf=null)}y(Va,Re);d=Va.prototype;d.te=function(){if(!this.Yl)throw Error("Tried to record the new position of a comment on the same event twice.");this.Xf=this.Yl.Pc.clone();this.Yl=null};d.type=B.i.so;
    d.ua=function(){var a=Va.m.ua.call(this);this.Xf&&(a.newCoordinate=Math.round(this.Xf.x)+","+Math.round(this.Xf.y));return a};d.Z=function(a){Va.m.Z.call(this,a);a.newCoordinate&&(a=a.newCoordinate.split(","),this.Xf=new A(parseFloat(a[0]),parseFloat(a[1])))};d.dh=function(){return Da(this.fn,this.Xf)};d.run=function(a){var b=Se($a(this),this.jd);if(b){a=a?this.Xf:this.fn;var c=b.Pc.clone();b.moveBy(a.x-c.x,a.y-c.y)}else console.warn("Can't move non-existent comment: "+this.jd)};function Te(a,b,c,e,f){this.id=f&&!Se(a,f)?f:B.h.Ed();a.Dh.push(this);a.Pj[this.id]&&console.warn('Overriding an existing comment on this workspace, with id "'+this.id+'"');a.Pj[this.id]=this;this.Pc=new A(0,0);this.xa=c;this.aa=e;this.o=a;this.s=a.s;this.Wi=this.ci=!0;this.Cc=b;this.xq=!0;Ue(this)}d=Te.prototype;
    d.v=function(){if(this.o){B.i.isEnabled()&&B.i.M(new Wa(this));var a=this.o;if(!xa(a.Dh,this))throw"Comment not present in workspace's list of top-most comments.";delete a.Pj[this.id];this.o=null}};d.Ug=function(){return this.xa};d.Fc=function(){return this.aa};d.moveBy=function(a,b){var c=new Va(this);this.Pc.translate(a,b);c.te();B.i.M(c)};d.Ob=function(){return this.ci&&!(this.o&&this.o.options.readOnly)};d.Qn=function(a){this.ci=a};d.Md=function(){return this.Wi&&!(this.o&&this.o.options.readOnly)};
    d.jg=function(a){this.Wi=a};d.qc=function(){return this.Cc};d.cd=function(a){this.Cc!=a&&(B.i.M(new Ua(this,this.Cc,a)),this.Cc=a)};d.nj=function(a){a=Ve(this,a);a.setAttribute("x",Math.round(this.Pc.x));a.setAttribute("y",Math.round(this.Pc.y));a.setAttribute("h",this.xa);a.setAttribute("w",this.aa);return a};function Ve(a,b){var c=C("comment");b||c.setAttribute("id",a.id);c.textContent=a.qc();return c}
    function Ue(a){if(B.i.isEnabled()){var b=B.i.$b();b||B.i.T(!0);try{B.i.M(new Ta(a))}finally{b||B.i.T(!1)}}}function We(a){var b=a.getAttribute("h"),c=a.getAttribute("w");return{id:a.getAttribute("id"),kq:b?parseInt(b,10):100,Zr:c?parseInt(c,10):100,x:parseInt(a.getAttribute("x"),10),y:parseInt(a.getAttribute("y"),10),content:a.textContent}};

    
    